Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -45,6 +45,10 @@ elif [ "$kernelName" == "Linux" ]; then
     exit 0
 elif [[ "$kernelName" == CYGWIN* ]] || [[ "$kernelName" == MINGW32* ]] || [[ "$kernelName" == MSYS* ]] || [[ "$kernelName" == MINGW* ]]; then
     echo "Windows OS detected"
+    if [[ -z "$MSYSTEM" || "$MSYSTEM" != "MINGW64" && "$MSYSTEM" != "MINGW32" ]]; then
+        echo "Error: This script must be run in Git Bash on Windows."
+        exit 1
+    fi
     python -m venv venv
     source venv/Scripts/activate
     python install.py
