Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,10 +5,17 @@ kernelName="$(uname -s)"
 curl https://raw.githubusercontent.com/zackees/install.py/main/install.py -o python
 
 if [ "$kernelName" == "Darwin" ]; then
-    brew install python@3.11
-    python3.11 -m venv venv
-    source venv/bin/activate
-    python install.py
+    # Check if Homebrew is installed
+    if command -v brew >/dev/null 2>&1; then
+        echo "Homebrew is installed. Continuing with installation."
+        brew install python@3.11
+        python3.11 -m venv venv
+        source venv/bin/activate
+        python install.py
+    else
+        echo "Error: Homebrew is not installed. Please install Homebrew and rerun this script."
+        exit 1
+    fi
 elif [ "$kernelName" == "Linux" ]; then
     sudo apt-get install python3.11
     python3.11 -m venv venv
@@ -19,5 +26,5 @@ elif [[ "$kernelName" == CYGWIN* ]] || [[ "$kernelName" == MINGW32* ]] || [[ "$k
 else
     # Error
     echo "Unknown operating system: $kernelName"
+    exit 1
 fi
-
